### ISSUE TITLE
Lab3

### ISSUE THREAD

**Issue by nboukhed** [mglantz/ansible-roadshow#44]
"Finally you need to apply the newly created role to your wildflyservers group. In dir $WORK_DIR create a file named site.yml. Put the following content into the file:"

Please introduce the concept of "role".

**Comment by jacobborella** [comment]
It is in the top of lab 3:

"In order to ensure that you don't end up with a large unmaintainable yaml-file, the lead architect of your company has decided that you must structure your playbook using roles. Roles is a way to structure your playbook around different aspects of your configuration. In this case, you will make a role for your wildfly application and only apply that role to your wildflyservers."
